# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estimator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='estimator.proto',
  package='config.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x65stimator.proto\x12\x0c\x63onfig.proto\"\xe0\x03\n\tEstimator\x12.\n\x06\x63onfig\x18\x01 \x02(\x0b\x32\x1e.config.proto.Estimator.Config\x1a\xa2\x03\n\x06\x43onfig\x12\x33\n\x05train\x18\x01 \x02(\x0b\x32$.config.proto.Estimator.Config.Train\x12\x31\n\x04\x64\x61ta\x18\x02 \x02(\x0b\x32#.config.proto.Estimator.Config.Data\x12>\n\x0bhidden_unit\x18\x03 \x03(\x0b\x32).config.proto.Estimator.Config.HiddenUnit\x1a\x38\n\x04\x44\x61ta\x12\x15\n\rsplit_percent\x18\x01 \x02(\x02\x12\x19\n\x11\x64irectory_pattern\x18\x02 \x02(\t\x1a\x1d\n\nHiddenUnit\x12\x0f\n\x07neurons\x18\x01 \x02(\x05\x1a\x96\x01\n\x05Train\x12\x1e\n\x16save_checkpoints_steps\x18\x01 \x02(\x05\x12\x11\n\tmodel_dir\x18\x02 \x02(\t\x12\x1a\n\x12\x65val_throttle_secs\x18\x03 \x02(\x05\x12\x13\n\x0btrain_steps\x18\x04 \x02(\x05\x12\x12\n\nbatch_size\x18\x05 \x02(\x05\x12\x15\n\rlearning_rate\x18\x06 \x02(\x02')
)




_ESTIMATOR_CONFIG_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='config.proto.Estimator.Config.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='split_percent', full_name='config.proto.Estimator.Config.Data.split_percent', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='directory_pattern', full_name='config.proto.Estimator.Config.Data.directory_pattern', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=330,
)

_ESTIMATOR_CONFIG_HIDDENUNIT = _descriptor.Descriptor(
  name='HiddenUnit',
  full_name='config.proto.Estimator.Config.HiddenUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neurons', full_name='config.proto.Estimator.Config.HiddenUnit.neurons', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=361,
)

_ESTIMATOR_CONFIG_TRAIN = _descriptor.Descriptor(
  name='Train',
  full_name='config.proto.Estimator.Config.Train',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='save_checkpoints_steps', full_name='config.proto.Estimator.Config.Train.save_checkpoints_steps', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_dir', full_name='config.proto.Estimator.Config.Train.model_dir', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_throttle_secs', full_name='config.proto.Estimator.Config.Train.eval_throttle_secs', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_steps', full_name='config.proto.Estimator.Config.Train.train_steps', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='config.proto.Estimator.Config.Train.batch_size', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='config.proto.Estimator.Config.Train.learning_rate', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=514,
)

_ESTIMATOR_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='config.proto.Estimator.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train', full_name='config.proto.Estimator.Config.train', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='config.proto.Estimator.Config.data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hidden_unit', full_name='config.proto.Estimator.Config.hidden_unit', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ESTIMATOR_CONFIG_DATA, _ESTIMATOR_CONFIG_HIDDENUNIT, _ESTIMATOR_CONFIG_TRAIN, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=514,
)

_ESTIMATOR = _descriptor.Descriptor(
  name='Estimator',
  full_name='config.proto.Estimator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='config.proto.Estimator.config', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ESTIMATOR_CONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=514,
)

_ESTIMATOR_CONFIG_DATA.containing_type = _ESTIMATOR_CONFIG
_ESTIMATOR_CONFIG_HIDDENUNIT.containing_type = _ESTIMATOR_CONFIG
_ESTIMATOR_CONFIG_TRAIN.containing_type = _ESTIMATOR_CONFIG
_ESTIMATOR_CONFIG.fields_by_name['train'].message_type = _ESTIMATOR_CONFIG_TRAIN
_ESTIMATOR_CONFIG.fields_by_name['data'].message_type = _ESTIMATOR_CONFIG_DATA
_ESTIMATOR_CONFIG.fields_by_name['hidden_unit'].message_type = _ESTIMATOR_CONFIG_HIDDENUNIT
_ESTIMATOR_CONFIG.containing_type = _ESTIMATOR
_ESTIMATOR.fields_by_name['config'].message_type = _ESTIMATOR_CONFIG
DESCRIPTOR.message_types_by_name['Estimator'] = _ESTIMATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Estimator = _reflection.GeneratedProtocolMessageType('Estimator', (_message.Message,), dict(

  Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(

    Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
      DESCRIPTOR = _ESTIMATOR_CONFIG_DATA,
      __module__ = 'estimator_pb2'
      # @@protoc_insertion_point(class_scope:config.proto.Estimator.Config.Data)
      ))
    ,

    HiddenUnit = _reflection.GeneratedProtocolMessageType('HiddenUnit', (_message.Message,), dict(
      DESCRIPTOR = _ESTIMATOR_CONFIG_HIDDENUNIT,
      __module__ = 'estimator_pb2'
      # @@protoc_insertion_point(class_scope:config.proto.Estimator.Config.HiddenUnit)
      ))
    ,

    Train = _reflection.GeneratedProtocolMessageType('Train', (_message.Message,), dict(
      DESCRIPTOR = _ESTIMATOR_CONFIG_TRAIN,
      __module__ = 'estimator_pb2'
      # @@protoc_insertion_point(class_scope:config.proto.Estimator.Config.Train)
      ))
    ,
    DESCRIPTOR = _ESTIMATOR_CONFIG,
    __module__ = 'estimator_pb2'
    # @@protoc_insertion_point(class_scope:config.proto.Estimator.Config)
    ))
  ,
  DESCRIPTOR = _ESTIMATOR,
  __module__ = 'estimator_pb2'
  # @@protoc_insertion_point(class_scope:config.proto.Estimator)
  ))
_sym_db.RegisterMessage(Estimator)
_sym_db.RegisterMessage(Estimator.Config)
_sym_db.RegisterMessage(Estimator.Config.Data)
_sym_db.RegisterMessage(Estimator.Config.HiddenUnit)
_sym_db.RegisterMessage(Estimator.Config.Train)


# @@protoc_insertion_point(module_scope)
